assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^messenger/', include('messenger.urls')),
    url(r'^admin/', admin.site.urls),
]

messenger/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(prefix='conversation', viewset=views.ConversationViewSet)
router.register(prefix='message', viewset=views.MessageViewSet)
router.register(prefix='user', viewset=views.UserViewSet)

app_name = 'messenger'
urlpatterns = [
	# Account handling
	url(r'^register/$', views.register, name='register'),
	url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
	url(r'^login/$', auth_views.login, {'template_name': 'messenger/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'next_page': 'messenger:conversations'}, name='logout'),

	# Conversation handling
	url(r'^$', views.AllConversationsView.as_view(), name='conversations'),
	url(r'^conversations/(?P<conversation_id>[0-9]+)/$', views.ConversationView.as_view(), name="conversation"),
	url(r'^newconversation/$', views.NewConversationView.as_view(), name="newconversation"),

	# Message handling
	url(r'^leaveconversation/(?P<conversation_id>[0-9]+)/$', views.leave_conversation, name="leaveconversation"),
	url(r'^addparticipant/(?P<conversation_id>[0-9]+)/$', views.AddParticipantView.as_view(), name="addparticipant"),
	url(r'^removemessage/(?P<message_id>[0-9]+)/$', views.remove_message, name="removemessage"),
	url(r'^editmessage/(?P<message_id>[0-9]+)/$', views.EditMessageView.as_view(), name="editmessage"),
]
urlpatterns += router.urls

messenger/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Conversation(models.Model):
	participants = models.ManyToManyField(User)
	created = models.DateTimeField(auto_now=True)
	conversation_name = models.CharField(max_length=100)

	def __str__(self):
		return self.conversation_name


class Message(models.Model):
	sent_by = models.ForeignKey(User, related_name='sent_by')
	conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
	message_text = models.CharField(max_length=1000)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.message_text

messenger/forms.py
from django import forms
from .models import Conversation, Message
from django.contrib.auth.models import User


class MessageForm(forms.ModelForm):
	class Meta:
		model = Message
		fields = ('message_text',)
		widgets = {'message_text': forms.Textarea(attrs={'rows': 4})}

class NewConversationForm(forms.ModelForm):
	conversation_name = forms.CharField(max_length=100)

	class Meta:
		model = Conversation
		fields = ('conversation_name',)

class AddParticipantForm(forms.Form):
	username = forms.CharField(max_length=150)

	class Meta:
		fields = ('username',)

messenger/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.views.generic.edit import CreateView
from .models import Message, Conversation
from .forms import MessageForm, AddParticipantForm, NewConversationForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from .serializers import *
from .permissions import *
from rest_framework import viewsets

# Viewsets
class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class ConversationViewSet(viewsets.ModelViewSet):
	queryset = Conversation.objects.all()
	serializer_class = ConversationSerializer

class MessageViewSet(viewsets.ModelViewSet):
	queryset = Message.objects.all()
	serializer_class = MessageSerializer
	permission_classes = (IsOwnerOrReadOnly,)

	def pre_save(self, object):
		object.sent_by = self.request.user
		# Any time a message is added by a user, currently logged in user is set
		# as owner of the new message object

# Views
# All conversations
class AllConversationsView(generic.TemplateView):
	template_name = 'messenger/allconversations.html'

	def get(self, request):
		if request.user.is_authenticated():
			form = NewConversationForm()
			all_conversations = self.request.user.conversation_set.all().order_by('created')
			return render(request, self.template_name, {'form': form, 'all_conversations': all_conversations})
		else:
			return redirect('messenger:login')

	def post(self, request):
		form = NewConversationForm(request.POST)

		if form.is_valid():
			conversation = form.save()
			conversation.participants.add(self.request.user)
			conversation.save()
			return redirect('messenger:conversation', conversation.pk)

# Single conversation
class ConversationView(generic.TemplateView):
	template_name = 'messenger/conversation.html'

	def get(self, request, conversation_id):
		conversation = Conversation.objects.get(pk=conversation_id)
		participants = conversation.participants.all()
		messages = conversation.message_set.all().order_by('timestamp')
		messageform = MessageForm()
		participantform = AddParticipantForm()
		return render(request, 'messenger/conversation.html',
			{'messageform': messageform, 'participantform': participantform, 'conversation': conversation, 'participants': participants, 'messages': messages, 'pk': conversation_id})

	def post(self, request, conversation_id):
		form = MessageForm(request.POST)

		if form.is_valid():
			message = form.save(commit=False)
			message.conversation = Conversation.objects.get(pk=conversation_id)
			message.sent_by = self.request.user
			message.save()
			return redirect('messenger:conversation', conversation_id)

# New conversation
class NewConversationView(generic.TemplateView):
	template_name = 'messenger/newconversation.html'

	def get(self, request):
		form = NewConversationForm()
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = NewConversationForm(request.POST)

		if form.is_valid():
			conversation = form.save()
			conversation.participants.add(self.request.user)
			conversation.save()
			return redirect('messenger:conversation', conversation.pk)

# Add participants to a conversation
class AddParticipantView(generic.TemplateView):
	template_name = 'messenger/addparticipant.html'

	def get(self, request, conversation_id):
		form = AddParticipantForm()
		conversation = get_object_or_404(Conversation, pk=conversation_id)
		return render(request, self.template_name, {'form': form, 'conversation': conversation})

	def post(self, request, conversation_id):
		form = AddParticipantForm(request.POST)
		conversation = get_object_or_404(Conversation, pk=conversation_id)

		if form.is_valid():
			username = form.cleaned_data['username']
			try:
				user = User.objects.get(username=username)
			except User.DoesNotExist:
				form = AddParticipantForm()
				return render(request, self.template_name,
					{'form': form, 'conversation': conversation, 'error': ('User ' + username + ' does not exist!')})

			conversation.participants.add(user)
			conversation.save()
			return redirect('messenger:conversation', conversation.pk)

		else:
			return render(request, 'messenger/error.html', {'error': 'something went terribly wrong'})

# Edit message
class EditMessageView(generic.TemplateView):
	template_name = 'messenger/editmessage.html'

	def get(self, request, message_id):
		message = get_object_or_404(Message, pk=message_id)

		if is_owner(request, message_id):
			form = MessageForm()
			return render(request, self.template_name, {'form': form})
		else:
			return render(request, 'messenger/error.html', {'error': 'You cannot edit messages that aren\'t yours.'})

	def post(self, request, message_id):
		message = get_object_or_404(Message, pk=message_id)
		conversation = message.conversation
		form = MessageForm(request.POST)

		if form.is_valid():
			message.message_text = request.POST['message_text']
			message.save()
			return redirect('messenger:conversation', conversation.pk)

def leave_conversation(request, conversation_id):
	conversation = Conversation.objects.get(pk=conversation_id)

	if conversation.participants.all().count() == 1: # If the user is the only one in the conversation, delete whole conversation
		conversation.delete()
	else:
		request.user.conversation_set.remove(conversation) # Otherwise just remove the user

	return redirect('messenger:conversations')

# Removes a message
def remove_message(request, message_id):
	message = get_object_or_404(Message, pk=message_id)
	conversation = message.conversation

	if is_owner(request, message_id):
		message.delete()
	else:
		return render(request, 'messenger/error.html', {'error': 'You cannot delete messages that aren\'t yours.'})

	return redirect('messenger:conversation', conversation.pk)

# Registers a new user and logs in
def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password2')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('messenger:conversations')
	else:
		form = UserCreationForm()

	return render(request, 'messenger/register.html', {'form': form})

# Helper methods
def validate_username(request):
	username = request.GET.get('username', None)
	data = {
		'is_taken': User.objects.filter(username__iexact=username).exists()
	}
	if data['is_taken']:
		data['error_message'] = "That username is already taken!"
	return JsonResponse(data)

def is_owner(request, message_id):
	return request.user == Message.objects.get(pk=message_id).sent_by

messenger/templates/messenger/addparticipant.html
{% extends 'messenger/base.html' %}

{% block title %}
	Add user to conversation
{% endblock %}

{% block content %}
	<h3>Add new participant to {{ conversation.conversation_name }}</h3>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Add to conversation</button>
	</form>

	<!-- Print error message if there is one -->
	<p style="font-size: 1.5em; color: red;">{{ error }}</p>
{% endblock %}

messenger/templates/messenger/allconversations.html
{% extends 'messenger/base.html' %}

{% block scripts %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href={% static 'messenger/css/allconversations.css' %} />
	<script src={% static 'messenger/js/allconversations.js' %}></script>
{% endblock %}

{% block content %}
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="headingleft">
					All conversations
					<button class="btn btn-primary headingright" onclick=(newConversation())>+</button>
				</h2>
			</div>
			<div class="panel-body">

				<!-- Container for the table itself -->
				{% if all_conversations %}
					<div class="table-container">
						<table class="table table-striped">
							<tbody>
								{% for conversation in all_conversations %}
									<tr>
										<th>
											<a href="{% url 'messenger:conversation' conversation.pk %}">
												{{ conversation.conversation_name }}
											</a>
										</th>
									<td>{{ conversation.created }}</td>
									</tr>
								{% endfor %}
						</tbody>
					</table>
				</div>
				{% else %}
					<div class="alert alert-info">
						<strong>Nothing to see here!</strong> You are not in any conversations right now.
					</div>
				{% endif %}
			</div>
		</div>

		<div id="newConversationForm">
			<h2>Start a conversation</h2>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-primary" type="submit">Start conversation</button>
			</form>
		</div>
	</div>
	
{% endblock %}

messenger/templates/messenger/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>
			{% block title %}
				Messenger
			{% endblock %}
		</title>
		<meta charset="utf-8" />

		{% load staticfiles %}
		<!-- Stylesheets -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Yantramanav" />
		<link rel="stylesheet" type="text/css" href={% static 'messenger/css/style.css' %} />

		<!-- JavaScript -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
	</head>

	<body>
		<div class="container">
			<!-- Navigation bar -->
			<nav class="navbar navbar-inverse">

				<!-- Navbar header -->
				<div class="navbar-header">
					<a class="navbar-brand" href="{% url 'messenger:conversations' %}">
						&emsp;<span class="glyphicon glyphicon-home"></span>&emsp;
					</a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<!-- Navbar items -->
				<div class="collapse navbar-collapse" id="navBar">
					<!-- Right floating -->
					<ul class="nav navbar-nav navbar-right">
						<!-- Log out -->
						<li class="">
							<a href="{% url 'messenger:logout' %}">
								&emsp;<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&emsp;
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<div class="col-md-12">
			{% block content %}
			{% endblock %}
			</div>
		</div>

		<!-- This is down here to ensure base scripts have already loaded -->
		{% block scripts %}
		{% endblock %}
	</body>
</html>

messenger/templates/messenger/conversation.html
{% extends 'messenger/base.html' %}

{% block title %}
  {% if conversation %}
    {{ conversation.conversation_name }}
  {% else %}
    No conversation found!
  {% endif %}
{% endblock %}

{% block scripts %}
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href={% static 'messenger/css/conversation.css' %} />
  <script src="{% static 'messenger/js/conversation.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="col-md-9" style="float: left;">


  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <h3 class="text-muted">
      		{{ conversation.conversation_name }}
      		<a style="float: right;" href="{% url 'messenger:leaveconversation' conversation.pk %}">Leave conversation</a>
      	</h3>
      </div>
    </div>
    <div class="panel-body">
      {% if messages %}
        {% for message in messages %}
          <div class="messagerow">
            <strong class="text-muted">{{ message.sent_by }}</strong>
            <small class="text-muted">{{ message.timestamp }}</small>
            <span style="float: right; padding-top: 5px;"
              <!-- Edit icon -->
  						<a href="{% url 'messenger:editmessage' message.pk %}">
  							<span class="glyphicon glyphicon-pencil"></span>
  						</a>
              <!-- Delete icon -->
  						<a href="{% url 'messenger:removemessage' message.pk %}">
  							<span class="glyphicon glyphicon-trash"></span>
  						</a>
            </span>
            <br />
            {{ message.message_text }}
          </div>
        {% endfor %}
        {% else %}
          <p>Nothing to see here...</p>
        {% endif %}
      </div>
    </div>

    <div>
        <!-- Form to send message in the selected conversation -->
        <form method="post" class="input">
          {% csrf_token %}
          {{ messageform.as_p }}
          <button type="submit" class="btn btn-primary" id="sendmessage">Send</button>
        </form>
      </div>
  </div>

  <!-- Right floaing participants section -->
  <div class="col-md-3" style="float: right;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">
          <h3 class="text-muted">
            Participants
          <form action="{% url 'messenger:addparticipant' conversation.pk %}" style="float: right;">
            <button class="btn btn-primary">+</button>
          </form>
          </h3>
        </div>
      </div>
      <div class="panel-body">
        {% if participants %}
      		<ul>
      			{% for p in participants %}
      				<li>{{ p.username }}</li>
      			{% endfor %}
      		</ul>
        {% endif %}
        
        <!-- Print error message if there is one -->
        <p style="font-size: 1.5em; color: red;">{{ error }}</p>
      </div>
    </div>
<!-- 
    <div class="addparticipant">
        <form method="post">
          {% csrf_token %}
          {{ participantform.as_p }}
          <button type="submit" class="btn btn-primary">Add to conversation</button>
        </form>
      </div>
  </div> -->

 

{% endblock %}

messenger/templates/messenger/editmessage.html
{% extends 'messenger/base.html' %}

{% block title %}
	Edit message
{% endblock %}

{% block content %}
	<h3>Edit message</h3>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Save</button>
	</form>
	
	<!-- Print error message if there is one -->
	<p style="font-size: 1.5em; color: red;">{{ error }}</p>
{% endblock %}

messenger/templates/messenger/error.html
{% extends 'messenger/base.html' %}

{% block content %}
	{{ error }}
{% endblock %}

messenger/templates/messenger/login.html
{% extends 'messenger/base.html' %}

{% block title %}
	Login
{% endblock %}

{% block content %}
	<p>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Login</button>
		</form>
	</p>
	<p>
		<a href="{% url 'messenger:register' %}">Not registered?</a>
	</p>
{% endblock %}

messenger/templates/messenger/newconversation.html
{% extends 'messenger/base.html' %}

{% block title %}
	Start a new conversation!
{% endblock %}

{% block content %}
	<h2>Start a conversation</h2>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Start conversation</button>
	</form>
{% endblock %}

messenger/templates/messenger/register.html
{% extends 'messenger/base.html' %}

{% block content %}
	<h3>Sign up</h3>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Sign up</button>
	</form>
{% endblock %}